// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eiivlbyndywsiieplcft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpaXZsYnluZHl3c2lpZXBsY2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3OTk1MzEsImV4cCI6MjA2MTM3NTUzMX0.2sXC2VO65owv5DT5DK8opQiP6BrMrnIFVde7oRir4fg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);